-- crud Categoria 
-- insert 
SET TERM !! ;

CREATE PROCEDURE SP_CATEGORIA_INSERT (
    P_NOMBRE          VARCHAR(100),
    P_DESCRIPCION     VARCHAR(200),
    P_TIPO            VARCHAR(20),
    P_ORDEN           INTEGER,
    P_CREADO_POR      VARCHAR(100)
)
RETURNS (
    ID_GENERADO INTEGER
)
AS
DECLARE VARIABLE V_ID INTEGER;
BEGIN
    /* Generar ID autoincremental */
    V_ID = GEN_ID(SEQ_CATEGORIA, 1);

    INSERT INTO CATEGORIA (
        ID_CATEGORIA,
        NOMBRE_CATEGORIA,
        DESCRIPCION,
        TIPO,
        ORDEN_PRESENTACION,
        CREADO_POR,
        MODIFICADO_POR,
        CREADO_EN,
        MODIFICADO_EN
    )
    VALUES (
        :V_ID,
        :P_NOMBRE,
        :P_DESCRIPCION,
        :P_TIPO,
        :P_ORDEN,
        :P_CREADO_POR,
        :P_CREADO_POR,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

    ID_GENERADO = :V_ID;
    SUSPEND;
END!!

SET TERM ; !!


--read all
SET TERM !! ;

CREATE PROCEDURE SP_CATEGORIA_LIST
RETURNS (
    ID_CAT INTEGER,
    NOMBRE VARCHAR(100),
    DESCRIP VARCHAR(200),
    TIPO VARCHAR(20),
    ORDEN INTEGER,
    ESTADO VARCHAR(20)
)
AS
BEGIN
    FOR
        SELECT 
            ID_CATEGORIA,
            NOMBRE_CATEGORIA,
            DESCRIPCION,
            TIPO,
            ORDEN_PRESENTACION,
            'ACTIVO'
        FROM CATEGORIA
        INTO :ID_CAT, :NOMBRE, :DESCRIP, :TIPO, :ORDEN, :ESTADO
    DO
        SUSPEND;
END!!

SET TERM ; !!

--read
SET TERM !! ;

CREATE PROCEDURE SP_CATEGORIA_GET (
    P_ID INTEGER
)
RETURNS (
    ID_CAT INTEGER,
    NOMBRE VARCHAR(100),
    DESCRIP VARCHAR(200),
    TIPO VARCHAR(20),
    ORDEN INTEGER,
    CREADO_EN TIMESTAMP
)
AS
BEGIN
    SELECT
        ID_CATEGORIA,
        NOMBRE_CATEGORIA,
        DESCRIPCION,
        TIPO,
        ORDEN_PRESENTACION,
        CREADO_EN
    FROM CATEGORIA
    WHERE ID_CATEGORIA = :P_ID
    INTO
        :ID_CAT,
        :NOMBRE,
        :DESCRIP,
        :TIPO,
        :ORDEN,
        :CREADO_EN;

    SUSPEND;
END!!

SET TERM ; !!

--update 
SET TERM !! ;

CREATE PROCEDURE SP_CATEGORIA_UPDATE (
    P_ID INTEGER,
    P_NOMBRE VARCHAR(100),
    P_DESCRIPCION VARCHAR(200),
    P_TIPO VARCHAR(20),
    P_ORDEN INTEGER,
    P_MODIFICADO_POR VARCHAR(100)
)
AS
BEGIN
    UPDATE CATEGORIA
    SET 
        NOMBRE_CATEGORIA = :P_NOMBRE,
        DESCRIPCION = :P_DESCRIPCION,
        TIPO = :P_TIPO,
        ORDEN_PRESENTACION = :P_ORDEN,
        MODIFICADO_POR = :P_MODIFICADO_POR,
        MODIFICADO_EN = CURRENT_TIMESTAMP
    WHERE ID_CATEGORIA = :P_ID;
END!!

SET TERM ; !!


--delete

SET TERM ^ ;

CREATE PROCEDURE SP_CATEGORIA_DELETE (
    P_ID_CATEGORIA INTEGER,
    P_MODIFICADO_POR VARCHAR(100)
)
AS
DECLARE VARIABLE V_TMP INTEGER;
BEGIN
    V_TMP = NULL;

    SELECT 1
    FROM SUBCATEGORIA
    WHERE ID_CATEGORIA = :P_ID_CATEGORIA
    ROWS 1
    INTO :V_TMP;

    IF (V_TMP IS NOT NULL) THEN
        EXCEPTION EX_CATEGORIA_CON_SUBCATEGORIAS;

    UPDATE CATEGORIA
    SET
        MODIFICADO_POR = :P_MODIFICADO_POR,
        MODIFICADO_EN = CURRENT_TIMESTAMP
    WHERE ID_CATEGORIA = :P_ID_CATEGORIA;
END^

SET TERM ; ^

CREATE EXCEPTION EX_CATEGORIA_CON_SUBCATEGORIAS
'No se puede eliminar la categoria porque tiene subcategorias asociadas';
