-- CRUD TRANSACCION 
-- INSERT 
SET TERM !! ;

CREATE PROCEDURE SP_TRANSACCION_INSERT (
    P_ID_USUARIO INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_ID_OBLIGACION INTEGER,
    P_TIPO VARCHAR(20),
    P_ANO INTEGER,
    P_MES INTEGER,
    P_DESCRIPCION VARCHAR(200),
    P_MONTO NUMERIC(10,2),
    P_FECHA DATE,
    P_METODO_PAGO VARCHAR(50),
    P_NUM_FACTURA VARCHAR(50),
    P_OBSERVACIONES VARCHAR(200),
    P_CREADO_POR VARCHAR(100)
)
RETURNS (
    ID_GENERADO INTEGER
)
AS
DECLARE VARIABLE V_ID INTEGER;
BEGIN
    /* Generar ID autoincremental */
    V_ID = GEN_ID(SEQ_TRANSACCION, 1);

    INSERT INTO TRANSACCION (
        ID_TRANSACCION,
        ID_USUARIO,
        ID_PRESUPUESTO,
        ID_SUBCATEGORIA,
        ID_OBLIGACION,
        TIPO,
        ANO,
        MES,
        DESCRIPCION,
        MONTO,
        FECHA,
        METODO_PAGO,
        NUM_FACTURA,
        OBSERVACIONES,
        FECHA_REGISTRO,
        CREADO_POR,
        MODIFICADO_POR,
        CREADO_EN,
        MODIFICADO_EN
    )
    VALUES (
        :V_ID,
        :P_ID_USUARIO,
        :P_ID_PRESUPUESTO,
        :P_ID_SUBCATEGORIA,
        :P_ID_OBLIGACION,
        :P_TIPO,
        :P_ANO,
        :P_MES,
        :P_DESCRIPCION,
        :P_MONTO,
        :P_FECHA,
        :P_METODO_PAGO,
        :P_NUM_FACTURA,
        :P_OBSERVACIONES,
        CURRENT_TIMESTAMP,
        :P_CREADO_POR,
        :P_CREADO_POR,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

    ID_GENERADO = :V_ID;
    SUSPEND;
END!!

SET TERM ; !!

-- LIST 
SET TERM !! ;

CREATE PROCEDURE SP_TRANSACCION_LIST (
    P_ID_USUARIO INTEGER
)
RETURNS (
    ID_TRANS INTEGER,
    SUBCAT INTEGER,
    PRES INTEGER,
    TIPO VARCHAR(20),
    MONTO NUMERIC(10,2),
    FECHA DATE,
    DESCRI VARCHAR(200)
)
AS
BEGIN
    FOR
        SELECT
            ID_TRANSACCION,
            ID_SUBCATEGORIA,
            ID_PRESUPUESTO,
            TIPO,
            MONTO,
            FECHA,
            DESCRIPCION
        FROM TRANSACCION
        WHERE ID_USUARIO = :P_ID_USUARIO
        INTO
            :ID_TRANS,
            :SUBCAT,
            :PRES,
            :TIPO,
            :MONTO,
            :FECHA,
            :DESCRI
    DO
        SUSPEND;
END!!

SET TERM ; !!

-- GET 
SET TERM !! ;

CREATE PROCEDURE SP_TRANSACCION_GET (
    P_ID INTEGER
)
RETURNS (
    ID_TRANS INTEGER,
    USUARIO INTEGER,
    PRES INTEGER,
    SUBCAT INTEGER,
    OBL INTEGER,
    TIPO VARCHAR(20),
    ANO_I INTEGER,
    MES_I INTEGER,
    DESCRI VARCHAR(200),
    MONTO NUMERIC(10,2),
    FECHA DATE,
    METODO VARCHAR(50),
    FACTURA VARCHAR(50),
    OBS VARCHAR(200),
    REGISTRO TIMESTAMP
)
AS
BEGIN
    SELECT
        ID_TRANSACCION,
        ID_USUARIO,
        ID_PRESUPUESTO,
        ID_SUBCATEGORIA,
        ID_OBLIGACION,
        TIPO,
        ANO,
        MES,
        DESCRIPCION,
        MONTO,
        FECHA,
        METODO_PAGO,
        NUM_FACTURA,
        OBSERVACIONES,
        FECHA_REGISTRO
    FROM TRANSACCION
    WHERE ID_TRANSACCION = :P_ID
    INTO
        :ID_TRANS,
        :USUARIO,
        :PRES,
        :SUBCAT,
        :OBL,
        :TIPO,
        :ANO_I,
        :MES_I,
        :DESCRI,
        :MONTO,
        :FECHA,
        :METODO,
        :FACTURA,
        :OBS,
        :REGISTRO;

    SUSPEND;
END!!

SET TERM ; !!

-- UPDATE 
SET TERM !! ;

CREATE PROCEDURE SP_TRANSACCION_UPDATE (
    P_ID INTEGER,
    P_DESCRIPCION VARCHAR(200),
    P_MONTO NUMERIC(10,2),
    P_FECHA DATE,
    P_METODO VARCHAR(50),
    P_OBSERVACIONES VARCHAR(200),
    P_MODIFICADO_POR VARCHAR(100)
)
AS
BEGIN
    UPDATE TRANSACCION
    SET
        DESCRIPCION = :P_DESCRIPCION,
        MONTO = :P_MONTO,
        FECHA = :P_FECHA,
        METODO_PAGO = :P_METODO,
        OBSERVACIONES = :P_OBSERVACIONES,
        MODIFICADO_POR = :P_MODIFICADO_POR,
        MODIFICADO_EN = CURRENT_TIMESTAMP
    WHERE ID_TRANSACCION = :P_ID;
END!!

SET TERM ; !!

/*-- DELETE 
SET TERM !! ;

CREATE PROCEDURE SP_TRANSACCION_DELETE (
    P_ID INTEGER
)
AS
BEGIN
    DELETE FROM TRANSACCION
    WHERE ID_TRANSACCION = :P_ID;
END!!

SET TERM ; !!
*/