-- CRUD Subcategoria 
-- INSERT 
SET TERM !! ;

CREATE PROCEDURE SP_SUBCATEGORIA_INSERT (
    P_ID_CATEGORIA     INTEGER,
    P_NOMBRE           VARCHAR(100),
    P_DESCRIPCION      VARCHAR(200),
    P_ACTIVA           SMALLINT,
    P_ES_DEFECTO       SMALLINT,
    P_CREADO_POR       VARCHAR(100)
)
RETURNS (
    ID_GENERADO INTEGER
)
AS
DECLARE VARIABLE V_ID INTEGER;
BEGIN
    /* Generar ID autoincremental con el generador correcto */
    V_ID = GEN_ID(GEN_SUBCATEGORIA_ID, 1);

    INSERT INTO SUBCATEGORIA (
        ID_SUBCATEGORIA,
        ID_CATEGORIA,
        NOMBRE_SUBCATEGORIA,
        DESCRIPCION,
        ACTIVA,
        ES_DEFECTO,
        CREADO_POR,
        MODIFICADO_POR,
        CREADO_EN,
        MODIFICADO_EN
    )
    VALUES (
        :V_ID,
        :P_ID_CATEGORIA,
        :P_NOMBRE,
        :P_DESCRIPCION,
        :P_ACTIVA,
        :P_ES_DEFECTO,
        :P_CREADO_POR,
        :P_CREADO_POR,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

    ID_GENERADO = :V_ID;
    SUSPEND;
END!!

SET TERM ; !!

-- LIST 

SET TERM !! ;

CREATE PROCEDURE SP_SUBCATEGORIA_LIST
RETURNS (
    ID_SUB INTEGER,
    ID_CAT INTEGER,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(200),
    ACTIVA SMALLINT,
    DEFECTO SMALLINT,
    CREADO_EN TIMESTAMP
)
AS
BEGIN
    FOR
        SELECT 
            ID_SUBCATEGORIA,
            ID_CATEGORIA,
            NOMBRE_SUBCATEGORIA,
            DESCRIPCION,
            ACTIVA,
            ES_DEFECTO,
            CREADO_EN
        FROM SUBCATEGORIA
        INTO 
            :ID_SUB,
            :ID_CAT,
            :NOMBRE,
            :DESCRIPCION,
            :ACTIVA,
            :DEFECTO,
            :CREADO_EN
    DO
        SUSPEND;
END!!

SET TERM ; !!

-- READ
SET TERM !! ;

CREATE PROCEDURE SP_SUBCATEGORIA_GET (
    P_ID INTEGER
)
RETURNS (
    ID_SUB INTEGER,
    ID_CAT INTEGER,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(200),
    ACTIVA SMALLINT,
    DEFECTO SMALLINT,
    CREADO_EN TIMESTAMP
)
AS
BEGIN
    SELECT
        ID_SUBCATEGORIA,
        ID_CATEGORIA,
        NOMBRE_SUBCATEGORIA,
        DESCRIPCION,
        ACTIVA,
        ES_DEFECTO,
        CREADO_EN
    FROM SUBCATEGORIA
    WHERE ID_SUBCATEGORIA = :P_ID
    INTO
        :ID_SUB,
        :ID_CAT,
        :NOMBRE,
        :DESCRIPCION,
        :ACTIVA,
        :DEFECTO,
        :CREADO_EN;

    SUSPEND;
END!!

SET TERM ; !!

--UPDATE 

SET TERM !! ;

CREATE PROCEDURE SP_SUBCATEGORIA_UPDATE (
    P_ID INTEGER,
    P_NOMBRE VARCHAR(100),
    P_DESCRIPCION VARCHAR(200),
    P_ACTIVA SMALLINT,
    P_DEFECTO SMALLINT,
    P_MODIFICADO_POR VARCHAR(100)
)
AS
BEGIN
    UPDATE SUBCATEGORIA
    SET
        NOMBRE_SUBCATEGORIA = :P_NOMBRE,
        DESCRIPCION = :P_DESCRIPCION,
        ACTIVA = :P_ACTIVA,
        ES_DEFECTO = :P_DEFECTO,
        MODIFICADO_POR = :P_MODIFICADO_POR,
        MODIFICADO_EN = CURRENT_TIMESTAMP
    WHERE ID_SUBCATEGORIA = :P_ID;
END!!

SET TERM ; !!

--DELETE

SET TERM !! ;

CREATE PROCEDURE SP_SUBCATEGORIA_DELETE (
    P_ID INTEGER
)
AS
BEGIN
    DELETE FROM SUBCATEGORIA
    WHERE ID_SUBCATEGORIA = :P_ID;
END!!

SET TERM ; !!

