-- obligacion fija 
-- insert 
SET TERM !! ;

CREATE PROCEDURE SP_OBLIGACION_INSERT (
    P_ID_USUARIO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_NOMBRE VARCHAR(150),
    P_DESCRIPCION VARCHAR(200),
    P_MONTO NUMERIC(10,2),
    P_DIA_VENC INTEGER,
    P_VIGENTE SMALLINT,
    P_FECHA_INICIO DATE,
    P_FECHA_FIN DATE,
    P_CREADO_POR VARCHAR(100)
)
RETURNS (
    ID_GENERADO INTEGER
)
AS
DECLARE VARIABLE V_ID INTEGER;
BEGIN
    /* Generar ID automático */
    V_ID = GEN_ID(SEQ_OBLIGACION, 1);

    INSERT INTO OBLIGACION_FIJA (
        ID_OBLIGACION,
        ID_USUARIO,
        ID_SUBCATEGORIA,
        NOMBRE_OBLIGACION,
        DESCRIPCION,
        MONTO_MENSUAL,
        DIA_VENCIMIENTO,
        VIGENTE,
        FECHA_INICIO,
        FECHA_FIN,
        CREADO_POR,
        MODIFICADO_POR,
        CREADO_EN,
        MODIFICADO_EN
    )
    VALUES (
        :V_ID,
        :P_ID_USUARIO,
        :P_ID_SUBCATEGORIA,
        :P_NOMBRE,
        :P_DESCRIPCION,
        :P_MONTO,
        :P_DIA_VENC,
        :P_VIGENTE,
        :P_FECHA_INICIO,
        :P_FECHA_FIN,
        :P_CREADO_POR,
        :P_CREADO_POR,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

    ID_GENERADO = :V_ID;
    SUSPEND;
END!!

SET TERM ; !!


-- list
SET TERM !! ;

CREATE PROCEDURE SP_OBLIGACION_LIST (
    P_ID_USUARIO INTEGER
)
RETURNS (
    ID_OBL INTEGER,
    SUBCAT INTEGER,
    NOMBRE VARCHAR(150),
    MONTO NUMERIC(10,2),
    VIG SMALLINT,
    INICIO DATE
)
AS
BEGIN
    FOR
        SELECT
            ID_OBLIGACION,
            ID_SUBCATEGORIA,
            NOMBRE_OBLIGACION,
            MONTO_MENSUAL,
            VIGENTE,
            FECHA_INICIO
        FROM OBLIGACION_FIJA
        WHERE ID_USUARIO = :P_ID_USUARIO
        INTO
            :ID_OBL,
            :SUBCAT,
            :NOMBRE,
            :MONTO,
            :VIG,
            :INICIO
    DO
        SUSPEND;
END!!

SET TERM ; !!

-- get 
SET TERM !! ;

CREATE PROCEDURE SP_OBLIGACION_GET (
    P_ID INTEGER
)
RETURNS (
    ID_OBL INTEGER,
    USUARIO INTEGER,
    SUBCAT INTEGER,
    NOMBRE VARCHAR(150),
    DESCRI VARCHAR(200),
    MONTO NUMERIC(10,2),
    DIA INTEGER,
    VIG SMALLINT,
    F_INI DATE,
    F_FIN DATE
)
AS
BEGIN
    SELECT
        ID_OBLIGACION,
        ID_USUARIO,
        ID_SUBCATEGORIA,
        NOMBRE_OBLIGACION,
        DESCRIPCION,
        MONTO_MENSUAL,
        DIA_VENCIMIENTO,
        VIGENTE,
        FECHA_INICIO,
        FECHA_FIN
    FROM OBLIGACION_FIJA
    WHERE ID_OBLIGACION = :P_ID
    INTO
        :ID_OBL,
        :USUARIO,
        :SUBCAT,
        :NOMBRE,
        :DESCRI,
        :MONTO,
        :DIA,
        :VIG,
        :F_INI,
        :F_FIN;

    SUSPEND;
END!!

SET TERM ; !!

-- update 
SET TERM !! ;

CREATE PROCEDURE SP_OBLIGACION_UPDATE (
    P_ID INTEGER,
    P_NOMBRE VARCHAR(150),
    P_DESCRIPCION VARCHAR(200),
    P_MONTO NUMERIC(10,2),
    P_DIA_VENC INTEGER,
    P_VIGENTE SMALLINT,
    P_FECHA_FIN DATE,
    P_MODIFICADO_POR VARCHAR(100)
)
AS
BEGIN
    UPDATE OBLIGACION_FIJA
    SET
        NOMBRE_OBLIGACION = :P_NOMBRE,
        DESCRIPCION = :P_DESCRIPCION,
        MONTO_MENSUAL = :P_MONTO,
        DIA_VENCIMIENTO = :P_DIA_VENC,
        VIGENTE = :P_VIGENTE,
        FECHA_FIN = :P_FECHA_FIN,
        MODIFICADO_POR = :P_MODIFICADO_POR,
        MODIFICADO_EN = CURRENT_TIMESTAMP
    WHERE ID_OBLIGACION = :P_ID;
END!!

SET TERM ; !!

-- delete 
SET TERM !! ;

CREATE PROCEDURE SP_OBLIGACION_DELETE (
    P_ID INTEGER
)
AS
BEGIN
    DELETE FROM OBLIGACION_FIJA
    WHERE ID_OBLIGACION = :P_ID;
END!!

SET TERM ; !!
