-- crud Presupuesto 
-- insert 
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_INSERT (
    P_ID_USUARIO INTEGER,
    P_NOMBRE VARCHAR(100),
    P_ANO_INICIO INTEGER,
    P_MES_INICIO INTEGER,
    P_ANO_FIN INTEGER,
    P_MES_FIN INTEGER,
    P_INGRESOS NUMERIC(10,2),
    P_GASTOS NUMERIC(10,2),
    P_AHORRO NUMERIC(10,2),
    P_ESTADO VARCHAR(20),
    P_CREADO_POR VARCHAR(100)
)
RETURNS (
    ID_GENERADO INTEGER
)
AS
DECLARE VARIABLE V_ID INTEGER;
BEGIN
    /* Generar ID automático */
    V_ID = GEN_ID(SEQ_PRESUPUESTO, 1);

    INSERT INTO PRESUPUESTO (
        ID_PRESUPUESTO,
        ID_USUARIO,
        NOMBRE_PRESUPUESTO,
        ANO_INICIO,
        MES_INICIO,
        ANO_FIN,
        MES_FIN,
        TOTAL_INGRESOS_PLANIFICADOS,
        TOTAL_GASTOS_PLANIFICADOS,
        TOTAL_AHORRO_PLANIFICADO,
        FECHA_CREACION,
        ESTADO,
        CREADO_POR,
        CREADO_EN,
        MODIFICADO_EN
    )
    VALUES (
        :V_ID,
        :P_ID_USUARIO,
        :P_NOMBRE,
        :P_ANO_INICIO,
        :P_MES_INICIO,
        :P_ANO_FIN,
        :P_MES_FIN,
        :P_INGRESOS,
        :P_GASTOS,
        :P_AHORRO,
        CURRENT_TIMESTAMP,
        :P_ESTADO,
        :P_CREADO_POR,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

    ID_GENERADO = :V_ID;
    SUSPEND;
END!!

SET TERM ; !!

-- list 
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_LIST
RETURNS (
    ID_PRES INTEGER,
    USUARIO INTEGER,
    NOMBRE VARCHAR(100),
    ANO_INI INTEGER,
    MES_INI INTEGER,
    ANO_FIN INTEGER,
    MES_FIN INTEGER,
    INGRESOS NUMERIC(10,2),
    GASTOS NUMERIC(10,2),
    AHORRO NUMERIC(10,2),
    ESTADO VARCHAR(20)
)
AS
BEGIN
    FOR
        SELECT
            ID_PRESUPUESTO,
            ID_USUARIO,
            NOMBRE_PRESUPUESTO,
            ANO_INICIO,
            MES_INICIO,
            ANO_FIN,
            MES_FIN,
            TOTAL_INGRESOS_PLANIFICADOS,
            TOTAL_GASTOS_PLANIFICADOS,
            TOTAL_AHORRO_PLANIFICADO,
            ESTADO
        FROM PRESUPUESTO
        INTO
            :ID_PRES,
            :USUARIO,
            :NOMBRE,
            :ANO_INI,
            :MES_INI,
            :ANO_FIN,
            :MES_FIN,
            :INGRESOS,
            :GASTOS,
            :AHORRO,
            :ESTADO
    DO
        SUSPEND;
END!!

SET TERM ; !!


-- get 
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_GET (
    P_ID INTEGER
)
RETURNS (
    ID_PRES INTEGER,
    USUARIO INTEGER,
    NOMBRE VARCHAR(100),
    ANO_INI INTEGER,
    MES_INI INTEGER,
    ANO_FIN INTEGER,
    MES_FIN INTEGER,
    INGRESOS NUMERIC(10,2),
    GASTOS NUMERIC(10,2),
    AHORRO NUMERIC(10,2),
    ESTADO VARCHAR(20),
    FECHA TIMESTAMP
)
AS
BEGIN
    SELECT
        ID_PRESUPUESTO,
        ID_USUARIO,
        NOMBRE_PRESUPUESTO,
        ANO_INICIO,
        MES_INICIO,
        ANO_FIN,
        MES_FIN,
        TOTAL_INGRESOS_PLANIFICADOS,
        TOTAL_GASTOS_PLANIFICADOS,
        TOTAL_AHORRO_PLANIFICADO,
        ESTADO,
        FECHA_CREACION
    FROM PRESUPUESTO
    WHERE ID_PRESUPUESTO = :P_ID
    INTO
        :ID_PRES,
        :USUARIO,
        :NOMBRE,
        :ANO_INI,
        :MES_INI,
        :ANO_FIN,
        :MES_FIN,
        :INGRESOS,
        :GASTOS,
        :AHORRO,
        :ESTADO,
        :FECHA;

    SUSPEND;
END!!

SET TERM ; !!


-- update 
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_UPDATE (
    P_ID INTEGER,
    P_INGRESOS NUMERIC(10,2),
    P_GASTOS NUMERIC(10,2),
    P_AHORRO NUMERIC(10,2),
    P_ESTADO VARCHAR(20),
    P_MODIFICADO_POR VARCHAR(100)
)
AS
BEGIN
    UPDATE PRESUPUESTO
    SET
        TOTAL_INGRESOS_PLANIFICADOS = :P_INGRESOS,
        TOTAL_GASTOS_PLANIFICADOS = :P_GASTOS,
        TOTAL_AHORRO_PLANIFICADO = :P_AHORRO,
        ESTADO = :P_ESTADO,
        MODIFICADO_POR = :P_MODIFICADO_POR,
        MODIFICADO_EN = CURRENT_TIMESTAMP
    WHERE ID_PRESUPUESTO = :P_ID;
END!!

SET TERM ; !!


/*-- delete 
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_DELETE (
    P_ID INTEGER
)
AS
BEGIN
    DELETE FROM PRESUPUESTO
    WHERE ID_PRESUPUESTO = :P_ID;
END!!

SET TERM ; !!*/
