-- CRUD PRESUPUESTO_DETALLE
-- INSERT 
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_DETALLE_INSERT (
    P_ID_PRESUPUESTO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_MONTO NUMERIC(10,2),
    P_OBSERVACIONES VARCHAR(200),
    P_CREADO_POR VARCHAR(100)
)
RETURNS (
    ID_GENERADO INTEGER
)
AS
DECLARE VARIABLE V_ID INTEGER;
BEGIN
    /* Generar ID automático */
    V_ID = GEN_ID(SEQ_PRESUPUESTO_DETALLE, 1);

    INSERT INTO PRESUPUESTO_DETALLE (
        ID_DETALLE,
        ID_PRESUPUESTO,
        ID_SUBCATEGORIA,
        MONTO_MENSUAL_ASIGNADO,
        OBSERVACIONES,
        CREADO_POR,
        MODIFICADO_POR,
        CREADO_EN,
        MODIFICADO_EN
    )
    VALUES (
        :V_ID,
        :P_ID_PRESUPUESTO,
        :P_ID_SUBCATEGORIA,
        :P_MONTO,
        :P_OBSERVACIONES,
        :P_CREADO_POR,
        :P_CREADO_POR,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

    ID_GENERADO = :V_ID;
    SUSPEND;
END!!

SET TERM ; !!

-- LIST 
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_DETALLE_LIST (
    P_ID_PRESUPUESTO INTEGER
)
RETURNS (
    ID_DET INTEGER,
    SUBCAT INTEGER,
    MONTO NUMERIC(10,2),
    OBS VARCHAR(200),
    CREADO TIMESTAMP
)
AS
BEGIN
    FOR
        SELECT
            ID_DETALLE,
            ID_SUBCATEGORIA,
            MONTO_MENSUAL_ASIGNADO,
            OBSERVACIONES,
            CREADO_EN
        FROM PRESUPUESTO_DETALLE
        WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
        INTO
            :ID_DET,
            :SUBCAT,
            :MONTO,
            :OBS,
            :CREADO
    DO
        SUSPEND;
END!!

SET TERM ; !!


--GET
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_DETALLE_GET (
    P_ID INTEGER
)
RETURNS (
    ID_DET INTEGER,
    PRESUP INTEGER,
    SUBCAT INTEGER,
    MONTO NUMERIC(10,2),
    OBS VARCHAR(200),
    CREADO TIMESTAMP
)
AS
BEGIN
    SELECT
        ID_DETALLE,
        ID_PRESUPUESTO,
        ID_SUBCATEGORIA,
        MONTO_MENSUAL_ASIGNADO,
        OBSERVACIONES,
        CREADO_EN
    FROM PRESUPUESTO_DETALLE
    WHERE ID_DETALLE = :P_ID
    INTO
        :ID_DET,
        :PRESUP,
        :SUBCAT,
        :MONTO,
        :OBS,
        :CREADO;

    SUSPEND;
END!!

SET TERM ; !!

--UPDATE 
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_DETALLE_UPDATE (
    P_ID INTEGER,
    P_MONTO NUMERIC(10,2),
    P_OBSERVACIONES VARCHAR(200),
    P_MODIFICADO_POR VARCHAR(100)
)
AS
BEGIN
    UPDATE PRESUPUESTO_DETALLE
    SET
        MONTO_MENSUAL_ASIGNADO = :P_MONTO,
        OBSERVACIONES = :P_OBSERVACIONES,
        MODIFICADO_POR = :P_MODIFICADO_POR,
        MODIFICADO_EN = CURRENT_TIMESTAMP
    WHERE ID_DETALLE = :P_ID;
END!!

SET TERM ; !!

-- DELETE
SET TERM !! ;

CREATE PROCEDURE SP_PRESUPUESTO_DETALLE_DELETE (
    P_ID INTEGER
)
AS
BEGIN
    DELETE FROM PRESUPUESTO_DETALLE
    WHERE ID_DETALLE = :P_ID;
END!!

SET TERM ; !!
