SET TERM ; !!
SET TERM !! ;
--read
SET TERM !! ;

CREATE PROCEDURE SP_USUARIO_GET (
    P_ID INTEGER
)
RETURNS (
    ID_US INTEGER,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    CORREO VARCHAR(150),
    SALARIO NUMERIC(10,2),
    ESTADO VARCHAR(20),
    FECHA_REG TIMESTAMP
)
AS
BEGIN
    SELECT
        ID_USUARIO,
        NOMBRE,
        APELLIDO,
        CORREO_ELECTRONICO,
        SALARIO_MENSUAL_BASE,
        ESTADO,
        CREADO_EN          
    FROM USUARIO
    WHERE ID_USUARIO = :P_ID
    INTO
        :ID_US,
        :NOMBRE,
        :APELLIDO,
        :CORREO,
        :SALARIO,
        :ESTADO,
        :FECHA_REG;

    SUSPEND;
END!!

SET TERM ; !!


--update
SET TERM !! ;

CREATE PROCEDURE SP_USUARIO_UPDATE (
    P_ID INTEGER,
    P_NOMBRE VARCHAR(100),
    P_APELLIDO VARCHAR(100),
    P_CORREO VARCHAR(150),
    P_SALARIO NUMERIC(10,2),
    P_ESTADO VARCHAR(20),
    P_MODIFICADO_POR VARCHAR(100)
)
AS
BEGIN
    UPDATE USUARIO
    SET
        NOMBRE = :P_NOMBRE,
        APELLIDO = :P_APELLIDO,
        CORREO_ELECTRONICO = :P_CORREO,
        SALARIO_MENSUAL_BASE = :P_SALARIO,
        ESTADO = :P_ESTADO,
        MODIFICADO_POR = :P_MODIFICADO_POR,
        MODIFICADO_EN = CURRENT_TIMESTAMP
    WHERE ID_USUARIO = :P_ID;
END!!


--insert
SET TERM !! ;

CREATE PROCEDURE SP_USUARIO_INSERT (
    P_NOMBRE        VARCHAR(100),
    P_APELLIDO      VARCHAR(100),
    P_CORREO        VARCHAR(150),
    P_SALARIO_BASE  NUMERIC(10,2),
    P_ESTADO        VARCHAR(20),
    P_CREADO_POR    VARCHAR(100)
)
RETURNS (
    ID_GENERADO INTEGER
)
AS
DECLARE VARIABLE V_ID INTEGER;
BEGIN
    /* Generar el ID usando el generador SEQ_USUARIO */
    V_ID = GEN_ID(SEQ_USUARIO, 1);

    INSERT INTO USUARIO (
        ID_USUARIO,
        NOMBRE,
        APELLIDO,
        CORREO_ELECTRONICO,
        FECHA_REGISTRO,
        SALARIO_MENSUAL_BASE,
        ESTADO,
        CREADO_POR,
        CREADO_EN,
        MODIFICADO_EN
    )
    VALUES (
        :V_ID,
        :P_NOMBRE,
        :P_APELLIDO,
        :P_CORREO,
        CURRENT_DATE,
        :P_SALARIO_BASE,
        :P_ESTADO,
        :P_CREADO_POR,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

    /* Devolver el ID insertado */
    ID_GENERADO = :V_ID;
    SUSPEND;
END!!

SET TERM ; !!

--delete
SET TERM !! ;

CREATE PROCEDURE SP_USUARIO_DELETE (
    P_ID INTEGER
)
AS
BEGIN
    DELETE FROM USUARIO
    WHERE ID_USUARIO = :P_ID;
END!!

SET TERM ; !!


SET TERM ; !!

