--PLN 1
SET TERM !! ;

CREATE PROCEDURE SP_CALCULAR_MONTO_EJECUTADO (
    P_ID_SUBCATEGORIA INTEGER,
    P_ANO INTEGER,
    P_MES INTEGER
)
RETURNS (
    MONTO_EJECUTADO NUMERIC(10,2)
)
AS
BEGIN
    SELECT COALESCE(SUM(MONTO), 0)
    FROM TRANSACCION
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
      AND ANO = :P_ANO
      AND MES = :P_MES
    INTO :MONTO_EJECUTADO;

    SUSPEND;
END!!

SET TERM ; !!

--PLN 2

SET TERM !! ;

CREATE PROCEDURE SP_CALCULAR_PORCENTAJE_EJECUTADO (
    P_ID_SUBCATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANO INTEGER,
    P_MES INTEGER
)
RETURNS (
    PORCENTAJE NUMERIC(5,2)
)
AS
DECLARE VARIABLE V_ASIGNADO NUMERIC(10,2);
DECLARE VARIABLE V_EJECUTADO NUMERIC(10,2);
BEGIN
    SELECT MONTO_MENSUAL_ASIGNADO
    FROM PRESUPUESTO_DETALLE
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :V_ASIGNADO;

    SELECT COALESCE(SUM(MONTO),0)
    FROM TRANSACCION
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
      AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ANO = :P_ANO
      AND MES = :P_MES
    INTO :V_EJECUTADO;

    IF (V_ASIGNADO IS NULL OR V_ASIGNADO = 0) THEN
        PORCENTAJE = 0;
    ELSE
        PORCENTAJE = (V_EJECUTADO / V_ASIGNADO) * 100;

    SUSPEND;
END!!

SET TERM ; !!

-- FN 3
SET TERM !! ;

CREATE PROCEDURE SP_OBTENER_BALANCE_SUBCATEGORIA (
    P_ID_PRESUPUESTO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_ANO INTEGER,
    P_MES INTEGER
)
RETURNS (
    BALANCE NUMERIC(10,2)
)
AS
DECLARE VARIABLE V_ASIGNADO NUMERIC(10,2);
DECLARE VARIABLE V_EJECUTADO NUMERIC(10,2);
BEGIN
    SELECT MONTO_MENSUAL_ASIGNADO
    FROM PRESUPUESTO_DETALLE
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :V_ASIGNADO;

    SELECT COALESCE(SUM(MONTO),0)
    FROM TRANSACCION
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
      AND ID_PRESUPUESTO = :P_ID_PRESUPUESTO
      AND ANO = :P_ANO
      AND MES = :P_MES
    INTO :V_EJECUTADO;

    BALANCE = COALESCE(V_ASIGNADO,0) - COALESCE(V_EJECUTADO,0);
    SUSPEND;
END!!

SET TERM ; !!

--FN 4

SET TERM !! ;

CREATE PROCEDURE SP_TOTAL_CATEGORIA_MES (
    P_ID_CATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER
)
RETURNS (
    TOTAL_CATEGORIA NUMERIC(10,2)
)
AS
BEGIN
    SELECT COALESCE(SUM(PD.MONTO_MENSUAL_ASIGNADO),0)
    FROM PRESUPUESTO_DETALLE PD
    JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = PD.ID_SUBCATEGORIA
    WHERE S.ID_CATEGORIA = :P_ID_CATEGORIA
      AND PD.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    INTO :TOTAL_CATEGORIA;

    SUSPEND;
END!!

SET TERM ; !!

-- FN 5
SET TERM !! ;

CREATE PROCEDURE SP_TOTAL_EJECUTADO_CATEGORIA_MES (
    P_ID_CATEGORIA INTEGER,
    P_ANO INTEGER,
    P_MES INTEGER
)
RETURNS (
    TOTAL_EJECUTADO NUMERIC(10,2)
)
AS
BEGIN
    SELECT COALESCE(SUM(T.MONTO),0)
    FROM TRANSACCION T
    JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = T.ID_SUBCATEGORIA
    WHERE S.ID_CATEGORIA = :P_ID_CATEGORIA
      AND T.ANO = :P_ANO
      AND T.MES = :P_MES
    INTO :TOTAL_EJECUTADO;

    SUSPEND;
END!!

SET TERM ; !!

--FN 6 
SET TERM !! ;

CREATE PROCEDURE SP_DIAS_HASTA_VENCIMIENTO (
    P_ID_OBLIGACION INTEGER
)
RETURNS (
    DIAS_RESTANTES INTEGER
)
AS
DECLARE VARIABLE V_FECHA DATE;
BEGIN
    SELECT FECHA_FIN
    FROM OBLIGACION_FIJA
    WHERE ID_OBLIGACION = :P_ID_OBLIGACION
    INTO :V_FECHA;

    IF (V_FECHA IS NULL) THEN
        DIAS_RESTANTES = NULL;
    ELSE
        DIAS_RESTANTES = V_FECHA - CURRENT_DATE;

    SUSPEND;
END!!

SET TERM ; !!

-- FN 7 
SET TERM !! ;

CREATE PROCEDURE SP_VALIDAR_VIGENCIA_PRESUPUESTO (
    P_FECHA DATE,
    P_ID_PRESUPUESTO INTEGER
)
RETURNS (
    ES_VALIDO SMALLINT
)
AS
DECLARE VARIABLE V_INICIO DATE;
DECLARE VARIABLE V_FIN DATE;
BEGIN
    SELECT
        CAST(ANO_INICIO || '-' || MES_INICIO || '-01' AS DATE),
        CAST(ANO_FIN || '-' || MES_FIN || '-01' AS DATE)
    FROM PRESUPUESTO
    WHERE ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    INTO :V_INICIO, :V_FIN;

    IF (P_FECHA BETWEEN V_INICIO AND V_FIN) THEN
        ES_VALIDO = 1;
    ELSE
        ES_VALIDO = 0;

    SUSPEND;
END!!

SET TERM ; !!

--FN 8 
SET TERM !! ;

CREATE PROCEDURE SP_OBTENER_CATEGORIA_POR_SUBCATEGORIA (
    P_ID_SUBCATEGORIA INTEGER
)
RETURNS (
    ID_CATEGORIA INTEGER
)
AS
BEGIN
    SELECT ID_CATEGORIA
    FROM SUBCATEGORIA
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :ID_CATEGORIA;

    SUSPEND;
END!!

SET TERM ; !!

-- FN 9 
SET TERM !! ;

CREATE PROCEDURE SP_PROYECCION_GASTO_MENSUAL (
    P_ID_SUBCATEGORIA INTEGER,
    P_ANO INTEGER,
    P_MES INTEGER
)
RETURNS (
    PROYECCION NUMERIC(10,2)
)
AS
DECLARE VARIABLE V_EJECUTADO NUMERIC(10,2);
DECLARE VARIABLE V_DIA INTEGER;
BEGIN
    SELECT COALESCE(SUM(MONTO),0)
    FROM TRANSACCION
    WHERE ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
      AND ANO = :P_ANO
      AND MES = :P_MES
    INTO :V_EJECUTADO;

    V_DIA = EXTRACT(DAY FROM CURRENT_DATE);

    IF (V_DIA > 0) THEN
        PROYECCION = (V_EJECUTADO / V_DIA) * 30;
    ELSE
        PROYECCION = 0;

    SUSPEND;
END!!

SET TERM ; !!

-- FN 10

SET TERM !! ;

CREATE PROCEDURE SP_PROMEDIO_GASTO_SUBCATEGORIA (
    P_ID_USUARIO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_MESES INTEGER
)
RETURNS (
    PROMEDIO NUMERIC(10,2)
)
AS
BEGIN
    SELECT COALESCE(AVG(MONTO),0)
    FROM TRANSACCION
    WHERE ID_USUARIO = :P_ID_USUARIO
      AND ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    INTO :PROMEDIO;

    SUSPEND;
END!!

SET TERM ; !!
