/* ======= GENERADORES REQUERIDOS ======= */

CREATE GENERATOR SEQ_USUARIO;
CREATE GENERATOR SEQ_PRESUPUESTO;
CREATE GENERATOR SEQ_CATEGORIA;
/* SUBCATEGORIA YA EXISTE: GEN_SUBCATEGORIA_ID */
CREATE GENERATOR SEQ_PRESUPUESTO_DETALLE;
CREATE GENERATOR SEQ_OBLIGACION;
CREATE GENERATOR SEQ_TRANSACCION;
CREATE GENERATOR SEQ_META;

/* ======= OPCIONAL: Inicializar valores ======= */

SET GENERATOR SEQ_USUARIO TO 0;
SET GENERATOR SEQ_PRESUPUESTO TO 0;
SET GENERATOR SEQ_CATEGORIA TO 0;
SET GENERATOR GEN_SUBCATEGORIA_ID TO 0;
SET GENERATOR SEQ_PRESUPUESTO_DETALLE TO 0;
SET GENERATOR SEQ_OBLIGACION TO 0;
SET GENERATOR SEQ_TRANSACCION TO 0;
SET GENERATOR SEQ_META TO 0;

