--TRIGGER 1 SUBCATEGORIA 
SET TERM ^ ;

CREATE TRIGGER BI_SUBCATEGORIA_ID
FOR SUBCATEGORIA
ACTIVE BEFORE INSERT
AS
BEGIN
    IF (NEW.ID_SUBCATEGORIA IS NULL) THEN
        NEW.ID_SUBCATEGORIA = GEN_ID(GEN_SUBCATEGORIA_ID, 1);
END^

SET TERM ; ^

--TRIGGER 2 SUB GENERAL 

SET TERM ^ ;

CREATE TRIGGER TRG_CREAR_SUBCATEGORIA_DEFECTO
FOR CATEGORIA
ACTIVE AFTER INSERT
AS
BEGIN
    INSERT INTO SUBCATEGORIA (
        ID_SUBCATEGORIA,
        ID_CATEGORIA,
        NOMBRE_SUBCATEGORIA,
        DESCRIPCION,
        ACTIVA,
        ES_DEFECTO,
        CREADO_POR,
        CREADO_EN,
        MODIFICADO_EN
    )
    VALUES (
        GEN_ID(GEN_SUBCATEGORIA_ID, 1),
        NEW.ID_CATEGORIA,
        'General',
        'Subcategoría generada automáticamente',
        1,
        1,
        NEW.CREADO_POR,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );
END^

SET TERM ; ^

--TRIGGER 3 ACTUALIZAR META DE AHORRO 

SET TERM ^ ;

CREATE TRIGGER TRG_ACTUALIZAR_META_AHORRO
FOR TRANSACCION
ACTIVE AFTER INSERT
AS
DECLARE VARIABLE V_ID_META INTEGER;
DECLARE VARIABLE V_ACUMULADO NUMERIC(12,2);
DECLARE VARIABLE V_OBJETIVO NUMERIC(12,2);
BEGIN
    IF (NEW.TIPO = 'ahorro') THEN
    BEGIN
        SELECT ID_META, MONTO_ACUMULADO, MONTO_OBJETIVO
        FROM META_AHORRO
        WHERE ID_USUARIO = NEW.ID_USUARIO
          AND ESTADO = 'en_progreso'
        INTO :V_ID_META, :V_ACUMULADO, :V_OBJETIVO;

        IF (V_ID_META IS NOT NULL) THEN
        BEGIN
            UPDATE META_AHORRO
            SET MONTO_ACUMULADO = COALESCE(:V_ACUMULADO, 0) + NEW.MONTO,
                MODIFICADO_EN = CURRENT_TIMESTAMP
            WHERE ID_META = :V_ID_META;

            IF ((COALESCE(:V_ACUMULADO, 0) + NEW.MONTO) >= :V_OBJETIVO) THEN
                UPDATE META_AHORRO
                SET ESTADO = 'completada',
                    MODIFICADO_EN = CURRENT_TIMESTAMP
                WHERE ID_META = :V_ID_META;
        END
    END
END^

SET TERM ; ^


--TRIGGER 4 ALERTA PRESUPUESTO 
SET TERM ^ ;

CREATE TRIGGER TRG_ALERTAS_PRESUPUESTO
FOR TRANSACCION
ACTIVE AFTER INSERT
AS
DECLARE VARIABLE V_ASIGNADO NUMERIC(12,2);
DECLARE VARIABLE V_EJECUTADO NUMERIC(12,2);
DECLARE VARIABLE V_PORCENTAJE NUMERIC(5,2);
BEGIN
    SELECT MONTO_MENSUAL_ASIGNADO
    FROM PRESUPUESTO_DETALLE
    WHERE ID_PRESUPUESTO = NEW.ID_PRESUPUESTO
      AND ID_SUBCATEGORIA = NEW.ID_SUBCATEGORIA
    INTO :V_ASIGNADO;

    IF (V_ASIGNADO IS NOT NULL) THEN
    BEGIN
        SELECT SUM(MONTO)
        FROM TRANSACCION
        WHERE ID_PRESUPUESTO = NEW.ID_PRESUPUESTO
          AND ID_SUBCATEGORIA = NEW.ID_SUBCATEGORIA
          AND ANO = NEW.ANO
          AND MES = NEW.MES
        INTO :V_EJECUTADO;

        V_EJECUTADO = COALESCE(V_EJECUTADO, 0);
        V_PORCENTAJE = (V_EJECUTADO / V_ASIGNADO) * 100;

        IF (V_PORCENTAJE >= 80 AND V_PORCENTAJE < 100) THEN
            INSERT INTO ALERTA (
                ID_USUARIO, TIPO_ALERTA, TITULO, MENSAJE,
                PRIORIDAD, FECHA_CREACION, CREADO_EN
            )
            VALUES (
                NEW.ID_USUARIO,
                'presupuesto_80',
                'Presupuesto al 80%',
                'Se ha consumido el 80% del presupuesto mensual.',
                'advertencia',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );

        IF (V_PORCENTAJE >= 100) THEN
            INSERT INTO ALERTA (
                ID_USUARIO, TIPO_ALERTA, TITULO, MENSAJE,
                PRIORIDAD, FECHA_CREACION, CREADO_EN
            )
            VALUES (
                NEW.ID_USUARIO,
                'presupuesto_100',
                'Presupuesto agotado',
                'Has alcanzado o superado el presupuesto mensual.',
                'critica',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            );
    END
END^

SET TERM ; ^
